version: '3.8'

services:
  # ------------------------------------------------------------
  # 1. O Banco de Dados (Simulando o AWS RDS)
  # ------------------------------------------------------------
  database:
    image: mysql:8.0
    container_name: farmacia-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: farmacia_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Salva os dados mesmo se desligar o container

  # ------------------------------------------------------------
  # 2. Microsserviço: Produtos (Recurso Principal)
  # ------------------------------------------------------------
  products-service:
    build: ./products-service
    container_name: products-api
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - PORT=3001
      - DB_HOST=database # Nome do serviço acima
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=farmacia_db
    volumes:
      - ./products-service/src:/app/src # "Hot Reload": mudou o código, atualiza na hora

  # ------------------------------------------------------------
  # 3. Microsserviço: Clientes
  # ------------------------------------------------------------
  clients-service:
    build: ./clients-service
    container_name: clients-api
    ports:
      - "3002:3002"
    depends_on:
      - database
    environment:
      - PORT=3002
      - DB_HOST=database
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=farmacia_db
    volumes:
      - ./clients-service/src:/app/src

  # ------------------------------------------------------------
  # 4. Microsserviço: Autenticação
  # ------------------------------------------------------------
  auth-service:
    build: ./auth-service
    container_name: auth-api
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - PORT=3000
      - DB_HOST=database
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=farmacia_db
    volumes:
      - ./auth-service/src:/app/src

volumes:
  mysql_data: