version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: farmacia-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  products-service:
    build: ./products-service
    container_name: products-api
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - PORT=${PORT_PRODUCTS}
      - DB_HOST=database
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./products-service/src:/app/src

  clients-service:
    build: ./clients-service
    container_name: clients-api
    ports:
      - "3002:3002"
    depends_on:
      - database
    environment:
      - PORT=${PORT_CLIENTS}
      - DB_HOST=database
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./clients-service/src:/app/src

  auth-service:
    build: ./auth-service
    container_name: auth-api
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - PORT=${PORT_AUTH}
      - DB_HOST=database
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./auth-service/src:/app/src

volumes:
  mysql_data: