name: CI Pipeline - Tests & Reports

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

env:
  AWS_REGION: us-east-1
  BUCKET_NAME: farmacia-relatorios-bruno-vinicius-2026  

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, products-service, clients-service]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      working-directory: ./${{ matrix.service }}
      run: npm install

    - name: Run Linting (ESLint)
      working-directory: ./${{ matrix.service }}
      run: npm run lint

    - name: Run Tests with Coverage
      working-directory: ./${{ matrix.service }}
      run: npx jest --coverage

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload Coverage to S3
      working-directory: ./${{ matrix.service }}
      run: |
        aws s3 sync coverage/lcov-report/ s3://${{ env.BUCKET_NAME }}/coverage/${{ matrix.service }}/${{ github.sha }}/ --delete
        echo "Relat√≥rio salvo em: s3://${{ env.BUCKET_NAME }}/coverage/${{ matrix.service }}/${{ github.sha }}/index.html"
